# -*- coding: utf-8 -*-
"""kalku

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q52bN3HHof6IpSnQ3EvHboxldo7gMTQU
"""

import streamlit as st

# Konstanta
ONGKIR_KOREA = 2000      # dalam KRW
TAMBAHAN_TETAP = 5000    # dalam IDR
TAMBAHAN_DIBAGI = 10000  # dalam IDR

st.set_page_config(page_title="Kalkulator Harga Korea", page_icon="🇰🇷")

st.title("🇰🇷 Kalkulator Harga Korea → Harga Bersih (IDR)")

# Input
harga_input = st.number_input("💰 Harga produk (contoh: 0.1 = 1.000 KRW)", min_value=0.0, step=0.01, format="%.2f")
try:
    harga_input = float(harga_input_str)
except ValueError:
    harga_input = 0.0
pembeli = st.number_input("👥 Jumlah pembeli", min_value=1, step=1)
rate = st.number_input("💱 Rate KRW → IDR", min_value=0.0, step=0.1)

if st.button("🔎 Hitung Harga Bersih"):
    # Ubah input ke KRW (0.1 = 1000 KRW)
    harga_krw = harga_input * 10000

    # Hitung harga IDR
    harga_idr = harga_krw * rate
    ongkir_per_produk = (ONGKIR_KOREA / pembeli) * rate
    tambahan_per_produk = TAMBAHAN_DIBAGI / pembeli
    total = harga_idr + ongkir_per_produk + TAMBAHAN_TETAP + tambahan_per_produk

    # Hasil akhir
    st.success(f"✅ Harga Bersih per Produk: Rp {total:,.0f}")
